import type { Word } from "@/lib/types";

export const adjectives: Word[] = [
  { id: "gut", level: "A1", theme: "adjectives", lemma: "gut", pos: "adjective", translation: { ru: "хороший, хорошо", en: "good / well", uk: "хороший, добре" }, adjective: { comparative: "besser", superlative: "am besten" }, note: { ru: "Сравнение неправильное: gut – besser – am besten.", en: "Irregular comparison: gut – besser – am besten.", uk: "Неправильне порівняння: gut – besser – am besten." }, examples: [{ de: "Das Essen ist gut.", translation: { ru: "Еда хорошая.", en: "The food is good.", uk: "Їжа смачна." } }] },
  { id: "gross", level: "A1", theme: "adjectives", lemma: "groß", pos: "adjective", translation: { ru: "большой, высокий", en: "big / tall", uk: "великий, високий" }, adjective: { comparative: "größer", superlative: "am größten" }, examples: [{ de: "Berlin ist eine große Stadt.", translation: { ru: "Берлин — большой город.", en: "Berlin is a big city.", uk: "Берлін — велике місто." } }] },
  { id: "klein", level: "A1", theme: "adjectives", lemma: "klein", pos: "adjective", translation: { ru: "маленький", en: "small", uk: "маленький" }, adjective: { comparative: "kleiner", superlative: "am kleinsten" }, examples: [{ de: "Das Kind ist noch klein.", translation: { ru: "Ребёнок ещё маленький.", en: "The child is still small.", uk: "Дитина ще маленька." } }] },
  { id: "neu", level: "A1", theme: "adjectives", lemma: "neu", pos: "adjective", translation: { ru: "новый", en: "new", uk: "новий" }, adjective: { comparative: "neuer", superlative: "am neuesten" }, examples: [] },
  { id: "alt", level: "A1", theme: "adjectives", lemma: "alt", pos: "adjective", translation: { ru: "старый", en: "old", uk: "старий" }, adjective: { comparative: "älter", superlative: "am ältesten" }, examples: [] },
  { id: "schoen", level: "A1", theme: "adjectives", lemma: "schön", pos: "adjective", translation: { ru: "красивый; прекрасно", en: "beautiful / nice", uk: "гарний; чудово" }, adjective: { comparative: "schöner", superlative: "am schönsten" }, examples: [] },
];
