import type { Word } from "@/lib/types";

export const home: Word[] = [
  { id: "haus", level: "A1", theme: "home", lemma: "Haus", pos: "noun", translation: { ru: "дом", en: "house", uk: "дім; будинок" }, noun: { gender: "n", plural: "Häuser", genitiveSingular: "Hauses" }, examples: [{ de: "Das Haus ist alt.", translation: { ru: "Дом старый.", en: "The house is old.", uk: "Будинок старий." } }] },
  { id: "wohnung", level: "A1", theme: "home", lemma: "Wohnung", pos: "noun", translation: { ru: "квартира", en: "apartment / flat", uk: "квартира" }, noun: { gender: "f", plural: "Wohnungen" }, examples: [{ de: "Die Wohnung ist klein, aber schön.", translation: { ru: "Квартира маленькая, но красивая.", en: "The flat is small but nice.", uk: "Квартира маленька, але гарна." } }] },
  { id: "zimmer", level: "A1", theme: "home", lemma: "Zimmer", pos: "noun", translation: { ru: "комната", en: "room", uk: "кімната" }, noun: { gender: "n", plural: "Zimmer" }, examples: [] },
  { id: "kueche", level: "A1", theme: "home", lemma: "Küche", pos: "noun", translation: { ru: "кухня", en: "kitchen", uk: "кухня" }, noun: { gender: "f", plural: "Küchen" }, examples: [] },
  { id: "tisch", level: "A1", theme: "home", lemma: "Tisch", pos: "noun", translation: { ru: "стол", en: "table", uk: "стіл" }, noun: { gender: "m", plural: "Tische", genitiveSingular: "Tisches" }, examples: [{ de: "Der Tisch ist aus Holz.", translation: { ru: "Стол из дерева.", en: "The table is made of wood.", uk: "Стіл із дерева." } }] },
  { id: "stuhl", level: "A1", theme: "home", lemma: "Stuhl", pos: "noun", translation: { ru: "стул", en: "chair", uk: "стілець" }, noun: { gender: "m", plural: "Stühle" }, examples: [] },
  { id: "bett", level: "A1", theme: "home", lemma: "Bett", pos: "noun", translation: { ru: "кровать", en: "bed", uk: "ліжко" }, noun: { gender: "n", plural: "Betten" }, examples: [] },
  { id: "lampe", level: "A1", theme: "home", lemma: "Lampe", pos: "noun", translation: { ru: "лампа", en: "lamp", uk: "лампа" }, noun: { gender: "f", plural: "Lampen" }, examples: [{ de: "Die Lampe ist hell.", translation: { ru: "Лампа яркая.", en: "The lamp is bright.", uk: "Лампа яскрава." } }] },
  { id: "tuer", level: "A1", theme: "home", lemma: "Tür", pos: "noun", translation: { ru: "дверь", en: "door", uk: "двері" }, noun: { gender: "f", plural: "Türen" }, examples: [] },
  { id: "fenster", level: "A1", theme: "home", lemma: "Fenster", pos: "noun", translation: { ru: "окно", en: "window", uk: "вікно" }, noun: { gender: "n", plural: "Fenster" }, examples: [] },
  { id: "buch", level: "A1", theme: "home", lemma: "Buch", pos: "noun", translation: { ru: "книга", en: "book", uk: "книга; книжка" }, noun: { gender: "n", plural: "Bücher", genitiveSingular: "Buches" }, examples: [{ de: "Das Buch liegt auf dem Tisch.", translation: { ru: "Книга лежит на столе.", en: "The book is on the table.", uk: "Книга лежить на столі." } }] },
  { id: "schule", level: "A1", theme: "home", lemma: "Schule", pos: "noun", translation: { ru: "школа", en: "school", uk: "школа" }, noun: { gender: "f", plural: "Schulen" }, examples: [{ de: "Die Schule beginnt um acht.", translation: { ru: "Школа начинается в восемь.", en: "School starts at eight.", uk: "Школа починається о восьмій." } }] },
  { id: "hund", level: "A1", theme: "home", lemma: "Hund", pos: "noun", translation: { ru: "собака", en: "dog", uk: "собака; пес" }, noun: { gender: "m", plural: "Hunde" }, examples: [{ de: "Der Hund ist freundlich.", translation: { ru: "Собака дружелюбная.", en: "The dog is friendly.", uk: "Собака дружелюбний." } }] },
];
