import type { Word } from "@/lib/types";

export const verbs: Word[] = [
  { id: "sein", level: "A1", theme: "verbs", lemma: "sein", pos: "verb", translation: { ru: "быть", en: "to be", uk: "бути" }, verb: { praesens: { ich: "bin", du: "bist", erSieEs: "ist", wir: "sind", ihr: "seid", sieSie: "sind" }, partizipII: "gewesen", praeteritum3sg: "war", auxiliary: "sein", irregular: true }, examples: [{ de: "Ich bin froh.", translation: { ru: "Я рад.", en: "I am glad.", uk: "Я радий." } }] },
  { id: "haben", level: "A1", theme: "verbs", lemma: "haben", pos: "verb", translation: { ru: "иметь", en: "to have", uk: "мати" }, verb: { praesens: { ich: "habe", du: "hast", erSieEs: "hat", wir: "haben", ihr: "habt", sieSie: "haben" }, partizipII: "gehabt", praeteritum3sg: "hatte", auxiliary: "haben", irregular: true }, examples: [{ de: "Hast du Zeit?", translation: { ru: "У тебя есть время?", en: "Do you have time?", uk: "У тебе є час?" } }] },
  { id: "wohnen", level: "A1", theme: "verbs", lemma: "wohnen", pos: "verb", translation: { ru: "жить, проживать", en: "to live (reside)", uk: "жити, мешкати" }, verb: { praesens: { ich: "wohne", du: "wohnst", erSieEs: "wohnt", wir: "wohnen", ihr: "wohnt", sieSie: "wohnen" }, partizipII: "gewohnt", praeteritum3sg: "wohnte", auxiliary: "haben" }, examples: [{ de: "Ich wohne in München.", translation: { ru: "Я живу в Мюнхене.", en: "I live in Munich.", uk: "Я живу в Мюнхені." } }] },
  { id: "machen", level: "A1", theme: "verbs", lemma: "machen", pos: "verb", translation: { ru: "делать", en: "to do / make", uk: "робити" }, verb: { praesens: { ich: "mache", du: "machst", erSieEs: "macht", wir: "machen", ihr: "macht", sieSie: "machen" }, partizipII: "gemacht", praeteritum3sg: "machte", auxiliary: "haben" }, examples: [{ de: "Was machst du heute?", translation: { ru: "Что ты делаешь сегодня?", en: "What are you doing today?", uk: "Що ти робиш сьогодні?" } }] },
  { id: "lernen", level: "A1", theme: "verbs", lemma: "lernen", pos: "verb", translation: { ru: "учить, учиться", en: "to learn", uk: "вчити, вчитися" }, verb: { praesens: { ich: "lerne", du: "lernst", erSieEs: "lernt", wir: "lernen", ihr: "lernt", sieSie: "lernen" }, partizipII: "gelernt", praeteritum3sg: "lernte", auxiliary: "haben" }, examples: [{ de: "Wir lernen jeden Tag.", translation: { ru: "Мы учимся каждый день.", en: "We learn every day.", uk: "Ми вчимося щодня." } }] },
  { id: "kommen", level: "A1", theme: "verbs", lemma: "kommen", pos: "verb", translation: { ru: "приходить, приезжать", en: "to come", uk: "приходити, приїжджати" }, verb: { praesens: { ich: "komme", du: "kommst", erSieEs: "kommt", wir: "kommen", ihr: "kommt", sieSie: "kommen" }, partizipII: "gekommen", praeteritum3sg: "kam", auxiliary: "sein", irregular: true }, examples: [{ de: "Ich komme aus der Ukraine.", translation: { ru: "Я из Украины.", en: "I come from Ukraine.", uk: "Я з України." } }] },
  { id: "heissen", level: "A1", theme: "verbs", lemma: "heißen", pos: "verb", translation: { ru: "называться, зваться", en: "to be called", uk: "називатися, зватися" }, verb: { praesens: { ich: "heiße", du: "heißt", erSieEs: "heißt", wir: "heißen", ihr: "heißt", sieSie: "heißen" }, partizipII: "geheißen", praeteritum3sg: "hieß", auxiliary: "haben", irregular: true }, examples: [{ de: "Wie heißt du?", translation: { ru: "Как тебя зовут?", en: "What is your name?", uk: "Як тебе звати?" } }] },
  { id: "essen", level: "A1", theme: "verbs", lemma: "essen", pos: "verb", translation: { ru: "есть, кушать", en: "to eat", uk: "їсти" }, verb: { praesens: { ich: "esse", du: "isst", erSieEs: "isst", wir: "essen", ihr: "esst", sieSie: "essen" }, partizipII: "gegessen", praeteritum3sg: "aß", auxiliary: "haben", irregular: true }, note: { ru: "Меняет корень: e → i (du isst, er isst).", en: "Stem change e → i (du isst, er isst).", uk: "Змінює корінь: e → i (du isst, er isst)." }, examples: [{ de: "Er isst einen Apfel.", translation: { ru: "Он ест яблоко.", en: "He is eating an apple.", uk: "Він їсть яблуко." } }] },
  { id: "trinken", level: "A1", theme: "verbs", lemma: "trinken", pos: "verb", translation: { ru: "пить", en: "to drink", uk: "пити" }, verb: { praesens: { ich: "trinke", du: "trinkst", erSieEs: "trinkt", wir: "trinken", ihr: "trinkt", sieSie: "trinken" }, partizipII: "getrunken", praeteritum3sg: "trank", auxiliary: "haben", irregular: true }, examples: [{ de: "Ich trinke Kaffee.", translation: { ru: "Я пью кофе.", en: "I drink coffee.", uk: "Я п'ю каву." } }] },
  { id: "gehen", level: "A1", theme: "verbs", lemma: "gehen", pos: "verb", translation: { ru: "идти, ходить", en: "to go / walk", uk: "іти, ходити" }, verb: { praesens: { ich: "gehe", du: "gehst", erSieEs: "geht", wir: "gehen", ihr: "geht", sieSie: "gehen" }, partizipII: "gegangen", praeteritum3sg: "ging", auxiliary: "sein", irregular: true }, examples: [{ de: "Ich gehe nach Hause.", translation: { ru: "Я иду домой.", en: "I am going home.", uk: "Я йду додому." } }] },
  { id: "sprechen", level: "A1", theme: "verbs", lemma: "sprechen", pos: "verb", translation: { ru: "говорить", en: "to speak", uk: "говорити, розмовляти" }, verb: { praesens: { ich: "spreche", du: "sprichst", erSieEs: "spricht", wir: "sprechen", ihr: "sprecht", sieSie: "sprechen" }, partizipII: "gesprochen", praeteritum3sg: "sprach", auxiliary: "haben", irregular: true }, note: { ru: "Меняет корень: e → i (du sprichst, er spricht).", en: "Stem change e → i (du sprichst, er spricht).", uk: "Змінює корінь: e → i (du sprichst, er spricht)." }, examples: [{ de: "Sprichst du Deutsch?", translation: { ru: "Ты говоришь по-немецки?", en: "Do you speak German?", uk: "Ти говориш німецькою?" } }] },
  { id: "arbeiten", level: "A1", theme: "verbs", lemma: "arbeiten", pos: "verb", translation: { ru: "работать", en: "to work", uk: "працювати" }, verb: { praesens: { ich: "arbeite", du: "arbeitest", erSieEs: "arbeitet", wir: "arbeiten", ihr: "arbeitet", sieSie: "arbeiten" }, partizipII: "gearbeitet", praeteritum3sg: "arbeitete", auxiliary: "haben" }, note: { ru: "После основы на -t добавляется -e- (du arbeitest).", en: "An -e- is inserted after stems ending in -t (du arbeitest).", uk: "Після основи на -t додається -e- (du arbeitest)." }, examples: [{ de: "Wo arbeitest du?", translation: { ru: "Где ты работаешь?", en: "Where do you work?", uk: "Де ти працюєш?" } }] },
];
