import type { Word } from "@/lib/types";
import { v } from "./build";

const T = "verbs";
export const verbsExtra: Word[] = [
  v("geben", "давать", "to give", T),
  v("nehmen", "брать", "to take", T),
  v("sehen", "видеть", "to see", T),
  v("hören", "слышать, слушать", "to hear / listen", T),
  v("schreiben", "писать", "to write", T),
  v("sagen", "сказать", "to say", T),
  v("fragen", "спрашивать", "to ask", T),
  v("antworten", "отвечать", "to answer", T),
  v("verstehen", "понимать", "to understand", T),
  v("brauchen", "нуждаться", "to need", T),
  v("suchen", "искать", "to search", T),
  v("finden", "находить", "to find", T),
  v("helfen", "помогать", "to help", T),
  v("öffnen", "открывать", "to open", T),
  v("schließen", "закрывать", "to close", T),
  v("warten", "ждать", "to wait", T),
  v("bleiben", "оставаться", "to stay", T),
  v("stehen", "стоять", "to stand", T),
  v("sitzen", "сидеть", "to sit", T),
  v("liegen", "лежать", "to lie", T),
  v("schlafen", "спать", "to sleep", T),
  v("laufen", "бегать, идти", "to run / walk", T),
  v("bringen", "приносить", "to bring", T),
  v("denken", "думать", "to think", T),
  v("wissen", "знать (факт)", "to know (a fact)", T),
  v("kennen", "знать (быть знакомым)", "to know (be familiar)", T),
  v("beginnen", "начинать", "to begin", T),
  v("können", "мочь, уметь", "can / to be able", T),
  v("müssen", "быть должным", "must / to have to", T),
  v("wollen", "хотеть", "to want", T),
  v("möchten", "хотел бы", "would like", T),
  v("dürfen", "сметь, можно", "may / to be allowed", T),
  v("sollen", "следует", "should / ought to", T),
  v("mögen", "любить, нравиться", "to like", T),
];
