import type { Word } from "@/lib/types";
import { v } from "./build";

const T = "verbs";
export const verbsExtra: Word[] = [
  v("geben", "давать", "to give", T, "давати"),
  v("nehmen", "брать", "to take", T, "брати"),
  v("sehen", "видеть", "to see", T, "бачити"),
  v("hören", "слышать, слушать", "to hear / listen", T, "чути, слухати"),
  v("schreiben", "писать", "to write", T, "писати"),
  v("sagen", "сказать", "to say", T, "казати"),
  v("fragen", "спрашивать", "to ask", T, "запитувати"),
  v("antworten", "отвечать", "to answer", T, "відповідати"),
  v("verstehen", "понимать", "to understand", T, "розуміти"),
  v("brauchen", "нуждаться", "to need", T, "потребувати"),
  v("suchen", "искать", "to search", T, "шукати"),
  v("finden", "находить", "to find", T, "знаходити"),
  v("helfen", "помогать", "to help", T, "допомагати"),
  v("öffnen", "открывать", "to open", T, "відкривати"),
  v("schließen", "закрывать", "to close", T, "закривати"),
  v("warten", "ждать", "to wait", T, "чекати"),
  v("bleiben", "оставаться", "to stay", T, "залишатися"),
  v("stehen", "стоять", "to stand", T, "стояти"),
  v("sitzen", "сидеть", "to sit", T, "сидіти"),
  v("liegen", "лежать", "to lie", T, "лежати"),
  v("schlafen", "спать", "to sleep", T, "спати"),
  v("laufen", "бегать, идти", "to run / walk", T, "бігти, іти"),
  v("bringen", "приносить", "to bring", T, "приносити"),
  v("denken", "думать", "to think", T, "думати"),
  v("wissen", "знать (факт)", "to know (a fact)", T, "знати (факт)"),
  v("kennen", "знать (быть знакомым)", "to know (be familiar)", T, "знати (бути знайомим)"),
  v("beginnen", "начинать", "to begin", T, "починати"),
  v("können", "мочь, уметь", "can / to be able", T, "могти, вміти"),
  v("müssen", "быть должным", "must / to have to", T, "мусити"),
  v("wollen", "хотеть", "to want", T, "хотіти"),
  v("möchten", "хотел бы", "would like", T, "хотів би"),
  v("dürfen", "сметь, можно", "may / to be allowed", T, "могти, можна"),
  v("sollen", "следует", "should / ought to", T, "слід, мусити"),
  v("mögen", "любить, нравиться", "to like", T, "любити, подобатися"),
];
