import type { Exercise } from "@/lib/types";

export const exercises: Exercise[] = [
  {
    id: "ex-article-tisch",
    level: "A1",
    kind: "article-pick",
    prompt: { ru: "Какой артикль у слова «Tisch»?", en: "Which article does “Tisch” take?" },
    noun: "Tisch",
    correct: "m",
    explanation: { ru: "der Tisch — мужской род.", en: "der Tisch — masculine." },
    wordId: "tisch",
    grammarTopicId: "a1-articles",
  },
  {
    id: "ex-article-lampe",
    level: "A1",
    kind: "article-pick",
    prompt: { ru: "Какой артикль у слова «Lampe»?", en: "Which article does “Lampe” take?" },
    noun: "Lampe",
    correct: "f",
    explanation: { ru: "die Lampe — женский род.", en: "die Lampe — feminine." },
    wordId: "lampe",
    grammarTopicId: "a1-articles",
  },
  {
    id: "ex-article-buch",
    level: "A1",
    kind: "article-pick",
    prompt: { ru: "Какой артикль у слова «Buch»?", en: "Which article does “Buch” take?" },
    noun: "Buch",
    correct: "n",
    explanation: { ru: "das Buch — средний род.", en: "das Buch — neuter." },
    wordId: "buch",
    grammarTopicId: "a1-articles",
  },
  {
    id: "ex-conj-wohnen-ich",
    level: "A1",
    kind: "conjugation",
    prompt: { ru: "Проспрягайте «wohnen» для «ich».", en: "Conjugate “wohnen” for “ich”." },
    infinitive: "wohnen",
    person: "ich",
    accepted: ["wohne"],
    explanation: { ru: "ich wohne — основа wohn- + окончание -e.", en: "ich wohne — stem wohn- + ending -e." },
    grammarTopicId: "a1-present-regular",
    wordId: "wohnen",
  },
  {
    id: "ex-conj-machen-du",
    level: "A1",
    kind: "conjugation",
    prompt: { ru: "Проспрягайте «machen» для «du».", en: "Conjugate “machen” for “du”." },
    infinitive: "machen",
    person: "du",
    accepted: ["machst"],
    explanation: { ru: "du machst — окончание -st.", en: "du machst — ending -st." },
    grammarTopicId: "a1-present-regular",
    wordId: "machen",
  },
  {
    id: "ex-fill-sein-ich",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Вставьте правильную форму «sein».", en: "Insert the correct form of “sein”." },
    template: "Ich ___ Student.",
    accepted: ["bin"],
    explanation: { ru: "ich bin — форма «sein» для 1 лица.", en: "ich bin — the “sein” form for first person." },
    grammarTopicId: "a1-sein-haben",
    wordId: "sein",
  },
  {
    id: "ex-fill-haben-du",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Вставьте правильную форму «haben».", en: "Insert the correct form of “haben”." },
    template: "___ du Zeit?",
    accepted: ["Hast", "hast"],
    explanation: { ru: "du hast — форма «haben».", en: "du hast — the “haben” form." },
    grammarTopicId: "a1-sein-haben",
    wordId: "haben",
  },
  {
    id: "ex-mc-kommen",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Выберите правильную форму.", en: "Choose the correct form." },
    question: "Woher ___ du? — Ich komme aus Kyjiw.",
    options: ["kommst", "kommt", "kommen", "komme"],
    correctIndex: 0,
    explanation: { ru: "du kommst — 2 лицо ед. ч.", en: "du kommst — 2nd person singular." },
    grammarTopicId: "a1-present-regular",
    wordId: "kommen",
  },
  {
    id: "ex-trans-haus",
    level: "A1",
    kind: "translation",
    direction: "native->de",
    prompt: { ru: "Переведите на немецкий (с артиклем).", en: "Translate into German (with article)." },
    sourceNative: { ru: "дом", en: "the house" },
    accepted: ["das Haus"],
    explanation: { ru: "das Haus — средний род.", en: "das Haus — neuter." },
    wordId: "haus",
    grammarTopicId: "a1-articles",
  },
  {
    id: "ex-match-nouns",
    level: "A1",
    kind: "matching",
    prompt: { ru: "Сопоставьте слова и перевод.", en: "Match words to their translations." },
    pairs: [
      { de: "der Hund", native: { ru: "собака", en: "dog" } },
      { de: "die Frau", native: { ru: "женщина", en: "woman" } },
      { de: "das Kind", native: { ru: "ребёнок", en: "child" } },
      { de: "der Apfel", native: { ru: "яблоко", en: "apple" } },
    ],
    grammarTopicId: "a1-articles",
  },

  // --- Pronouns ---
  {
    id: "ex-pron-formal",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Вежливое обращение. Выберите местоимение.", en: "Polite address. Choose the pronoun." },
    question: "Wie heißen ___? — Ich heiße Frau Klein.",
    options: ["du", "Sie", "ihr", "er"],
    correctIndex: 1,
    explanation: { ru: "Sie — вежливая форма «Вы», всегда с большой буквы.", en: "Sie — the polite “you”, always capitalized." },
    grammarTopicId: "a1-pronouns",
  },
  {
    id: "ex-pron-ich",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Вставьте местоимение.", en: "Insert the pronoun." },
    template: "___ bin Student.",
    accepted: ["Ich", "ich"],
    explanation: { ru: "ich bin — 1-е лицо ед. ч.", en: "ich bin — first person singular." },
    grammarTopicId: "a1-pronouns",
  },

  // --- Stem-changing verbs ---
  {
    id: "ex-stem-sprechen",
    level: "A1",
    kind: "conjugation",
    prompt: { ru: "Проспрягайте «sprechen» для «er».", en: "Conjugate “sprechen” for “er”." },
    infinitive: "sprechen",
    person: "erSieEs",
    accepted: ["spricht"],
    explanation: { ru: "e → i: er spricht.", en: "e → i: er spricht." },
    grammarTopicId: "a1-stem-change",
  },
  {
    id: "ex-stem-fahren",
    level: "A1",
    kind: "conjugation",
    prompt: { ru: "Проспрягайте «fahren» для «du».", en: "Conjugate “fahren” for “du”." },
    infinitive: "fahren",
    person: "du",
    accepted: ["fährst"],
    explanation: { ru: "a → ä: du fährst.", en: "a → ä: du fährst." },
    grammarTopicId: "a1-stem-change",
  },

  // --- Modal verbs ---
  {
    id: "ex-modal-kann",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Вставьте «können» для «ich».", en: "Insert “können” for “ich”." },
    template: "Ich ___ gut schwimmen.",
    accepted: ["kann"],
    explanation: { ru: "ich kann — без окончания.", en: "ich kann — no ending." },
    grammarTopicId: "a1-modal-verbs",
  },
  {
    id: "ex-modal-musst",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Выберите правильную форму.", en: "Choose the correct form." },
    question: "Du ___ jetzt gehen.",
    options: ["muss", "musst", "müssen", "müsst"],
    correctIndex: 1,
    explanation: { ru: "du musst — 2-е лицо ед. ч.", en: "du musst — 2nd person singular." },
    grammarTopicId: "a1-modal-verbs",
  },

  // --- Akkusativ ---
  {
    id: "ex-akk-hund",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Винительный падеж. Выберите артикль.", en: "Accusative. Choose the article." },
    question: "Ich habe ___ Hund.",
    options: ["ein", "einen", "eine", "einem"],
    correctIndex: 1,
    explanation: { ru: "Мужской род в Akkusativ: ein → einen.", en: "Masculine in the accusative: ein → einen." },
    grammarTopicId: "a1-akkusativ",
  },
  {
    id: "ex-akk-mann",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Вставьте артикль (Akkusativ).", en: "Insert the article (accusative)." },
    template: "Ich sehe ___ Mann.",
    accepted: ["den"],
    explanation: { ru: "der → den (мужской род, Akkusativ).", en: "der → den (masculine, accusative)." },
    grammarTopicId: "a1-akkusativ",
  },

  // --- Dativ ---
  {
    id: "ex-dat-bus",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Вставьте артикль после «mit» (Dativ).", en: "Insert the article after “mit” (dative)." },
    template: "Ich fahre mit ___ Bus.",
    accepted: ["dem"],
    explanation: { ru: "mit + Dativ: der Bus → dem Bus.", en: "mit + dative: der Bus → dem Bus." },
    grammarTopicId: "a1-dativ",
  },
  {
    id: "ex-dat-dir",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Выберите местоимение.", en: "Choose the pronoun." },
    question: "Wie geht es ___?",
    options: ["du", "dich", "dir", "dein"],
    correctIndex: 2,
    explanation: { ru: "es geht dir — Dativ местоимения du.", en: "es geht dir — dative of du." },
    grammarTopicId: "a1-dativ",
  },

  // --- Possessives ---
  {
    id: "ex-poss-bruder",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Выберите притяжательный артикль (я).", en: "Choose the possessive (my)." },
    question: "Das ist ___ Bruder.",
    options: ["meine", "mein", "meinen", "meiner"],
    correctIndex: 1,
    explanation: { ru: "mein Bruder — мужской род, Nominativ.", en: "mein Bruder — masculine, nominative." },
    grammarTopicId: "a1-possessives",
  },
  {
    id: "ex-poss-familie",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Вставьте «мою» (ж. род, Akkusativ).", en: "Insert “my” (feminine, accusative)." },
    template: "Ich liebe ___ Familie.",
    accepted: ["meine"],
    explanation: { ru: "die Familie → meine Familie.", en: "die Familie → meine Familie." },
    grammarTopicId: "a1-possessives",
  },

  // --- Negation ---
  {
    id: "ex-neg-zeit",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Отрицание. Выберите слово.", en: "Negation. Choose the word." },
    question: "Ich habe ___ Zeit.",
    options: ["nicht", "kein", "keine", "keinen"],
    correctIndex: 2,
    explanation: { ru: "Существительное без артикля → kein; die Zeit → keine.", en: "Noun without article → kein; die Zeit → keine." },
    grammarTopicId: "a1-negation",
  },
  {
    id: "ex-neg-heute",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Отрицание глагола. Выберите слово.", en: "Negating a verb. Choose the word." },
    question: "Er kommt heute ___.",
    options: ["kein", "keine", "nicht", "nichts"],
    correctIndex: 2,
    explanation: { ru: "Глагол отрицается через nicht.", en: "A verb is negated with nicht." },
    grammarTopicId: "a1-negation",
  },

  // --- Separable verbs ---
  {
    id: "ex-sep-an",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Где приставка? (ankommen)", en: "Where is the prefix? (ankommen)" },
    template: "Der Zug kommt um 8 Uhr ___.",
    accepted: ["an"],
    explanation: { ru: "ankommen → приставка an в конце.", en: "ankommen → the prefix an goes to the end." },
    grammarTopicId: "a1-separable",
  },
  {
    id: "ex-sep-ein",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Где приставка? (einkaufen)", en: "Where is the prefix? (einkaufen)" },
    template: "Ich kaufe im Supermarkt ___.",
    accepted: ["ein"],
    explanation: { ru: "einkaufen → приставка ein в конце.", en: "einkaufen → the prefix ein goes to the end." },
    grammarTopicId: "a1-separable",
  },

  // --- Perfekt ---
  {
    id: "ex-perf-sind",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Выберите вспомогательный глагол.", en: "Choose the auxiliary verb." },
    question: "Wir ___ nach Berlin gefahren.",
    options: ["haben", "sind", "seid", "hat"],
    correctIndex: 1,
    explanation: { ru: "fahren — движение → sein: wir sind gefahren.", en: "fahren — motion → sein: wir sind gefahren." },
    grammarTopicId: "a1-perfekt",
  },
  {
    id: "ex-perf-gelernt",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Вставьте Partizip II (lernen).", en: "Insert the participle (lernen)." },
    template: "Ich habe Deutsch ___.",
    accepted: ["gelernt"],
    explanation: { ru: "lernen → gelernt (правильный глагол).", en: "lernen → gelernt (weak verb)." },
    grammarTopicId: "a1-perfekt",
  },

  // --- Word order & questions ---
  {
    id: "ex-wo-yesno",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Вопрос да/нет. Что на первом месте?", en: "Yes/no question. What comes first?" },
    question: "___ du in Berlin?",
    options: ["Du wohnst", "Wohnst", "Wo wohnst", "Wohnen"],
    correctIndex: 1,
    explanation: { ru: "В вопросе да/нет глагол на первом месте.", en: "In a yes/no question the verb comes first." },
    grammarTopicId: "a1-wordorder",
  },
  {
    id: "ex-wo-wfrage",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Вставьте вопросительное слово (что?).", en: "Insert the question word (what?)." },
    template: "___ machst du heute?",
    accepted: ["Was"],
    explanation: { ru: "Was = что. W-вопрос: слово + глагол.", en: "Was = what. W-question: word + verb." },
    grammarTopicId: "a1-wordorder",
  },

  // --- Conjunctions ---
  {
    id: "ex-conj-aber",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Выберите союз.", en: "Choose the conjunction." },
    question: "Die Wohnung ist klein, ___ schön.",
    options: ["und", "oder", "aber", "denn"],
    correctIndex: 2,
    explanation: { ru: "aber = но (противопоставление).", en: "aber = but (contrast)." },
    grammarTopicId: "a1-conjunctions",
  },
  {
    id: "ex-conj-denn",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Выберите союз.", en: "Choose the conjunction." },
    question: "Ich bleibe zu Hause, ___ ich bin krank.",
    options: ["und", "denn", "oder", "aber"],
    correctIndex: 1,
    explanation: { ru: "denn = потому что (причина).", en: "denn = because (reason)." },
    grammarTopicId: "a1-conjunctions",
  },

  // --- Imperative ---
  {
    id: "ex-imp-komm",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Форма «du» от kommen.", en: "The “du” form of kommen." },
    question: "___ bitte her!",
    options: ["Kommst", "Komm", "Kommen", "Kommt"],
    correctIndex: 1,
    explanation: { ru: "Императив du: основа без окончания — Komm!", en: "du imperative: bare stem — Komm!" },
    grammarTopicId: "a1-imperative",
  },
  {
    id: "ex-imp-sprechen",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Форма «Sie» от sprechen.", en: "The “Sie” form of sprechen." },
    template: "___ Sie bitte langsam!",
    accepted: ["Sprechen"],
    explanation: { ru: "Императив Sie: инфинитив + Sie.", en: "Sie imperative: infinitive + Sie." },
    grammarTopicId: "a1-imperative",
  },

  // --- Time expressions ---
  {
    id: "ex-time-halb",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Сколько времени: «halb drei»?", en: "What time is “halb drei”?" },
    question: "halb drei = ?",
    options: ["2:30", "3:30", "2:15", "3:00"],
    correctIndex: 0,
    explanation: { ru: "halb относится к следующему часу: halb drei = 2:30.", en: "halb points to the next hour: halb drei = 2:30." },
    grammarTopicId: "a1-time-expressions",
  },
  {
    id: "ex-time-um",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Вставьте предлог времени (точное время).", en: "Insert the time preposition (clock time)." },
    template: "Der Zug fährt ___ 8 Uhr.",
    accepted: ["um"],
    explanation: { ru: "um + точное время: um 8 Uhr.", en: "um + clock time: um 8 Uhr." },
    grammarTopicId: "a1-time-expressions",
  },
  {
    id: "ex-time-im",
    level: "A1",
    kind: "multiple-choice",
    prompt: { ru: "Выберите предлог (время года).", en: "Choose the preposition (season)." },
    question: "___ Sommer ist es warm.",
    options: ["am", "im", "um", "in"],
    correctIndex: 1,
    explanation: { ru: "im + время года/месяц: im Sommer.", en: "im + season/month: im Sommer." },
    grammarTopicId: "a1-time-expressions",
  },
  {
    id: "ex-time-am",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Вставьте предлог времени (день недели).", en: "Insert the time preposition (weekday)." },
    template: "___ Montag arbeite ich.",
    accepted: ["Am", "am"],
    explanation: { ru: "am + день недели: am Montag.", en: "am + weekday: am Montag." },
    grammarTopicId: "a1-time-expressions",
  },

  // --- Numbers & dates: write it in words ---
  {
    id: "ex-num-21",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Напишите число словами.", en: "Write the number in words." },
    template: "21 = ___",
    accepted: ["einundzwanzig"],
    explanation: { ru: "единицы + und + десятки: einundzwanzig.", en: "units + und + tens: einundzwanzig." },
    grammarTopicId: "a1-numbers-dates",
  },
  {
    id: "ex-num-47",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Напишите число словами.", en: "Write the number in words." },
    template: "47 = ___",
    accepted: ["siebenundvierzig"],
    explanation: { ru: "sieben + und + vierzig.", en: "sieben + und + vierzig." },
    grammarTopicId: "a1-numbers-dates",
  },
  {
    id: "ex-num-2014",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Напишите год словами.", en: "Write the year in words." },
    template: "2014 = ___",
    accepted: ["zweitausendvierzehn"],
    explanation: { ru: "С 2000 года: zweitausend + vierzehn.", en: "From 2000: zweitausend + vierzehn." },
    grammarTopicId: "a1-numbers-dates",
  },
  {
    id: "ex-num-1999",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Напишите год словами.", en: "Write the year in words." },
    template: "1999 = ___",
    accepted: ["neunzehnhundertneunundneunzig"],
    explanation: { ru: "До 2000 — через сотни: neunzehnhundert…", en: "Before 2000 use hundreds: neunzehnhundert…" },
    grammarTopicId: "a1-numbers-dates",
  },
  {
    id: "ex-date-erste",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Напишите дату словами.", en: "Write the date in words." },
    template: "Heute ist der 1. März. → der ___ März",
    accepted: ["erste"],
    explanation: { ru: "Порядковое: der erste (1.).", en: "Ordinal: der erste (1st)." },
    grammarTopicId: "a1-numbers-dates",
  },
  {
    id: "ex-date-dritten",
    level: "A1",
    kind: "fill-blank",
    prompt: { ru: "Напишите дату словами (после am).", en: "Write the date in words (after am)." },
    template: "am 3. Mai → am ___ Mai",
    accepted: ["dritten"],
    explanation: { ru: "После am порядковое + -en: am dritten.", en: "After am, ordinal + -en: am dritten." },
    grammarTopicId: "a1-numbers-dates",
  },
];
