import type { Lesson } from "@/lib/types";

// Grammar-focused lessons. Their `order` values use even slots so the
// auto-generated themed vocabulary lessons interleave between them.
export const grammarLessons: Lesson[] = [
  {
    id: "a1-l1",
    level: "A1",
    order: 2,
    title: { ru: "Урок: Род и артикли", en: "Lesson: Gender & articles" },
    goal: {
      ru: "Понять систему родов и научиться выбирать der/die/das.",
      en: "Understand the gender system and learn to pick der/die/das.",
    },
    steps: [
      { type: "grammar", topicId: "a1-articles" },
      { type: "vocab", wordIds: ["tisch", "lampe", "buch", "haus", "kind"] },
      { type: "exercise", exerciseId: "ex-article-tisch" },
      { type: "exercise", exerciseId: "ex-article-lampe" },
      { type: "exercise", exerciseId: "ex-article-buch" },
      { type: "exercise", exerciseId: "ex-trans-haus" },
      { type: "exercise", exerciseId: "ex-match-nouns" },
    ],
  },
  {
    id: "a1-l2",
    level: "A1",
    order: 5,
    title: { ru: "Урок: Настоящее время", en: "Lesson: Present tense" },
    goal: {
      ru: "Спрягать правильные глаголы и строить простые предложения.",
      en: "Conjugate regular verbs and build simple sentences.",
    },
    steps: [
      { type: "grammar", topicId: "a1-present-regular" },
      { type: "vocab", wordIds: ["wohnen", "machen", "lernen", "kommen", "heissen"] },
      { type: "exercise", exerciseId: "ex-conj-wohnen-ich" },
      { type: "exercise", exerciseId: "ex-conj-machen-du" },
      { type: "exercise", exerciseId: "ex-mc-kommen" },
    ],
  },
  {
    id: "a1-l3",
    level: "A1",
    order: 8,
    title: { ru: "Урок: sein и haben", en: "Lesson: sein & haben" },
    goal: {
      ru: "Выучить два ключевых неправильных глагола.",
      en: "Master the two key irregular verbs.",
    },
    steps: [
      { type: "grammar", topicId: "a1-sein-haben" },
      { type: "vocab", wordIds: ["sein", "haben", "gut", "gross"] },
      { type: "exercise", exerciseId: "ex-fill-sein-ich" },
      { type: "exercise", exerciseId: "ex-fill-haben-du" },
    ],
  },

  // --- Deeper A1 grammar (after the themed vocabulary units) ---
  {
    id: "a1-g-pronouns",
    level: "A1",
    order: 13,
    title: { ru: "Грамматика: Личные местоимения", en: "Grammar: Personal pronouns" },
    goal: { ru: "Различать du и Sie, освоить местоимения.", en: "Distinguish du and Sie; master the pronouns." },
    steps: [
      { type: "grammar", topicId: "a1-pronouns" },
      { type: "exercise", exerciseId: "ex-pron-ich" },
      { type: "exercise", exerciseId: "ex-pron-formal" },
    ],
  },
  {
    id: "a1-g-stem",
    level: "A1",
    order: 14,
    title: { ru: "Грамматика: Глаголы с изменением корня", en: "Grammar: Stem-changing verbs" },
    goal: { ru: "Спрягать глаголы с e→i и a→ä.", en: "Conjugate e→i and a→ä verbs." },
    steps: [
      { type: "grammar", topicId: "a1-stem-change" },
      { type: "exercise", exerciseId: "ex-stem-sprechen" },
      { type: "exercise", exerciseId: "ex-stem-fahren" },
    ],
  },
  {
    id: "a1-g-modal",
    level: "A1",
    order: 15,
    title: { ru: "Грамматика: Модальные глаголы", en: "Grammar: Modal verbs" },
    goal: { ru: "Строить предложения с können, müssen, möchten.", en: "Build sentences with können, müssen, möchten." },
    steps: [
      { type: "grammar", topicId: "a1-modal-verbs" },
      { type: "exercise", exerciseId: "ex-modal-kann" },
      { type: "exercise", exerciseId: "ex-modal-musst" },
    ],
  },
  {
    id: "a1-g-akkusativ",
    level: "A1",
    order: 16,
    title: { ru: "Грамматика: Винительный падеж", en: "Grammar: Accusative case" },
    goal: { ru: "Использовать den/einen в прямом дополнении.", en: "Use den/einen for the direct object." },
    steps: [
      { type: "grammar", topicId: "a1-akkusativ" },
      { type: "exercise", exerciseId: "ex-akk-hund" },
      { type: "exercise", exerciseId: "ex-akk-mann" },
    ],
  },
  {
    id: "a1-g-dativ",
    level: "A1",
    order: 17,
    title: { ru: "Грамматика: Дательный падеж (основы)", en: "Grammar: Dative (basics)" },
    goal: { ru: "Dativ после предлогов и mir/dir.", en: "Dative after prepositions and mir/dir." },
    steps: [
      { type: "grammar", topicId: "a1-dativ" },
      { type: "exercise", exerciseId: "ex-dat-bus" },
      { type: "exercise", exerciseId: "ex-dat-dir" },
    ],
  },
  {
    id: "a1-g-possessives",
    level: "A1",
    order: 18,
    title: { ru: "Грамматика: Притяжательные артикли", en: "Grammar: Possessive articles" },
    goal: { ru: "mein, dein, sein, ihr… и их формы.", en: "mein, dein, sein, ihr… and their forms." },
    steps: [
      { type: "grammar", topicId: "a1-possessives" },
      { type: "exercise", exerciseId: "ex-poss-bruder" },
      { type: "exercise", exerciseId: "ex-poss-familie" },
    ],
  },
  {
    id: "a1-g-negation",
    level: "A1",
    order: 19,
    title: { ru: "Грамматика: Отрицание nicht / kein", en: "Grammar: Negation nicht / kein" },
    goal: { ru: "Выбирать nicht или kein.", en: "Choose between nicht and kein." },
    steps: [
      { type: "grammar", topicId: "a1-negation" },
      { type: "exercise", exerciseId: "ex-neg-zeit" },
      { type: "exercise", exerciseId: "ex-neg-heute" },
    ],
  },
  {
    id: "a1-g-separable",
    level: "A1",
    order: 20,
    title: { ru: "Грамматика: Отделяемые глаголы", en: "Grammar: Separable verbs" },
    goal: { ru: "Ставить приставку в конец предложения.", en: "Put the prefix at the end of the sentence." },
    steps: [
      { type: "grammar", topicId: "a1-separable" },
      { type: "exercise", exerciseId: "ex-sep-an" },
      { type: "exercise", exerciseId: "ex-sep-ein" },
    ],
  },
  {
    id: "a1-g-perfekt",
    level: "A1",
    order: 21,
    title: { ru: "Грамматика: Прошедшее время (Perfekt)", en: "Grammar: Perfect tense" },
    goal: { ru: "haben/sein + Partizip II.", en: "haben/sein + past participle." },
    steps: [
      { type: "grammar", topicId: "a1-perfekt" },
      { type: "exercise", exerciseId: "ex-perf-sind" },
      { type: "exercise", exerciseId: "ex-perf-gelernt" },
    ],
  },
  {
    id: "a1-g-wordorder",
    level: "A1",
    order: 22,
    title: { ru: "Грамматика: Порядок слов и вопросы", en: "Grammar: Word order & questions" },
    goal: { ru: "Глагол на 2-м месте; строить вопросы.", en: "Verb in position 2; form questions." },
    steps: [
      { type: "grammar", topicId: "a1-wordorder" },
      { type: "exercise", exerciseId: "ex-wo-yesno" },
      { type: "exercise", exerciseId: "ex-wo-wfrage" },
    ],
  },
  {
    id: "a1-g-conjunctions",
    level: "A1",
    order: 23,
    title: { ru: "Грамматика: Союзы", en: "Grammar: Conjunctions" },
    goal: { ru: "und, oder, aber, denn.", en: "und, oder, aber, denn." },
    steps: [
      { type: "grammar", topicId: "a1-conjunctions" },
      { type: "exercise", exerciseId: "ex-conj-aber" },
      { type: "exercise", exerciseId: "ex-conj-denn" },
    ],
  },
  {
    id: "a1-g-imperative",
    level: "A1",
    order: 24,
    title: { ru: "Грамматика: Повелительное наклонение", en: "Grammar: Imperative" },
    goal: { ru: "Komm! Kommt! Kommen Sie!", en: "Komm! Kommt! Kommen Sie!" },
    steps: [
      { type: "grammar", topicId: "a1-imperative" },
      { type: "exercise", exerciseId: "ex-imp-komm" },
      { type: "exercise", exerciseId: "ex-imp-sprechen" },
    ],
  },
  {
    id: "a1-g-time",
    level: "A1",
    order: 25,
    title: { ru: "Грамматика: Время и даты", en: "Grammar: Telling time & dates" },
    goal: { ru: "Называть время и использовать um/am/im.", en: "Tell the time and use um/am/im." },
    steps: [
      { type: "grammar", topicId: "a1-time-expressions" },
      { type: "vocab", wordIds: ["uhr", "montag", "morgen", "abend"] },
      { type: "exercise", exerciseId: "ex-time-halb" },
      { type: "exercise", exerciseId: "ex-time-um" },
      { type: "exercise", exerciseId: "ex-time-im" },
      { type: "exercise", exerciseId: "ex-time-am" },
    ],
  },
  {
    id: "a1-g-numbers-dates",
    level: "A1",
    order: 26,
    title: { ru: "Грамматика: Числа и даты прописью", en: "Grammar: Writing numbers & dates" },
    goal: { ru: "Записывать числа, годы и даты словами.", en: "Write numbers, years and dates in words." },
    steps: [
      { type: "grammar", topicId: "a1-numbers-dates" },
      { type: "exercise", exerciseId: "ex-num-21" },
      { type: "exercise", exerciseId: "ex-num-47" },
      { type: "exercise", exerciseId: "ex-num-2014" },
      { type: "exercise", exerciseId: "ex-num-1999" },
      { type: "exercise", exerciseId: "ex-date-erste" },
      { type: "exercise", exerciseId: "ex-date-dritten" },
    ],
  },
];
